# Generated by Django 4.0.3 on 2022-04-11 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swarm_name', models.CharField(max_length=64, unique=True)),
                ('manager_join_token', models.CharField(blank=True, max_length=200, null=True)),
                ('worker_join_token', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=64)),
                ('service_id', models.CharField(max_length=64)),
                ('target_port', models.IntegerField()),
                ('published_port', models.IntegerField()),
                ('desired_replicas', models.IntegerField()),
                ('image_name', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('swarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarman.swarm')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('api_port', models.CharField(max_length=5)),
                ('role', models.CharField(max_length=16)),
                ('docker_version_index', models.CharField(max_length=16)),
                ('node_architecture', models.CharField(max_length=32)),
                ('node_id', models.CharField(max_length=200)),
                ('total_memory', models.FloatField(default=0)),
                ('cpu_count', models.IntegerField(default=0)),
                ('os', models.CharField(default='Unknown', max_length=32)),
                ('docker_engine', models.CharField(default='Unknown', max_length=16)),
                ('swarm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='swarman.swarm')),
            ],
        ),
        migrations.CreateModel(
            name='Mounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount_type', models.CharField(max_length=32)),
                ('mount_src', models.CharField(max_length=200)),
                ('mount_target', models.CharField(max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarman.service')),
            ],
        ),
    ]
