# Generated by Django 4.0.3 on 2022-03-25 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swarm_name', models.CharField(max_length=64)),
                ('manager_join_token', models.CharField(blank=True, max_length=200, null=True)),
                ('worker_join_token', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SwarmService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('role', models.CharField(max_length=16)),
                ('swarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='swarman.swarm')),
            ],
        ),
    ]
