# Generated by Django 4.0.3 on 2022-04-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarman', '0001_initial_squashed_0005_alter_swarm_swarm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_id',
            field=models.CharField(default='id', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='api_port',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='node',
            name='docker_version_index',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_architecture',
            field=models.CharField(max_length=32),
        ),
    ]
