# Generated by Django 4.0.3 on 2022-04-05 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swarman', '0002_node_node_id_alter_node_api_port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount_type', models.CharField(max_length=32)),
                ('mount_src', models.CharField(max_length=200)),
                ('mount_target', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=64)),
                ('service_id', models.CharField(max_length=64)),
                ('target_port', models.IntegerField()),
                ('published_port', models.IntegerField()),
                ('desired_replicas', models.IntegerField()),
                ('image_name', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('swarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarman.swarm')),
            ],
        ),
        migrations.DeleteModel(
            name='SwarmService',
        ),
        migrations.AddField(
            model_name='node',
            name='cpu_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='total_memory',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mounts',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swarman.service'),
        ),
    ]
