# Generated by Django 4.0.3 on 2022-03-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarman', '0003_node_docker_version_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_architecture',
            field=models.CharField(default='test', max_length=32),
            preserve_default=False,
        ),
    ]
