# Generated by Django 4.0.3 on 2022-04-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarman', '0003_mounts_service_delete_swarmservice_node_cpu_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='docker_engine',
            field=models.CharField(default='Unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='node',
            name='os',
            field=models.CharField(default='Unknown', max_length=32),
        ),
    ]
