# Generated by Django 4.0.3 on 2022-04-05 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swarman', '0004_node_docker_engine_node_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='swarm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='swarman.swarm'),
        ),
    ]
