# Generated by Django 4.0.3 on 2022-03-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swarman', '0004_node_node_architecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swarm',
            name='swarm_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
